import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { EntryForm } from "~/components/EntryForm";
import { Container } from "~/components/ui/container";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Emoji Summon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-white to-slate-200">
        <Container>
          <div className="mx-auto max-w-2xl lg:mx-0">
            <h2 className="my-2 w-full text-center text-3xl font-bold tracking-tight text-gray-900 sm:text-6xl">
              Emoji summon generator
            </h2>
          </div>
          <EntryForm />
        </Container>
      </main>
    </>
  );
};

export default Home;
