import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { EntryForm } from "~/components/EntryForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Emoji Summon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-white to-slate-200">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-slate-950 sm:text-[5rem]">
            Emoji Summon Generator
          </h1>
          <EntryForm />
        </div>
      </main>
    </>
  );
};

export default Home;
